// This file is auto-generated by @hey-api/openapi-ts

export enum KindEnum {
  BOOL = "bool",
  STR = "str",
  FLOAT = "float",
  INT = "int",
  SINGLE = "single",
  MULTI = "multi",
  INTEXT = "intext",
}

export enum AssignmentStatusEnum {
  FULL = "FULL",
  PARTIAL = "PARTIAL",
  OPEN = "OPEN",
  INVALID = "INVALID",
}

export enum BotKindEnum {
  CLASSIFICATION = "CLASSIFICATION",
  RULES = "RULES",
  TOPICS = "TOPICS",
  RESOLVE = "RESOLVE",
  SCRIPT = "SCRIPT",
}

export enum EventEnum {
  EXAMPLE_SUB_EVENT = "ExampleSubEvent",
  EXAMPLE_EVENT = "ExampleEvent",
}

export enum FieldEnum {
  TITLE = "title",
  ABSTRACT = "abstract",
  PUB_YEAR = "pub_year",
  DATE = "date",
  SOURCE = "source",
}

export enum ItemTypeEnum {
  GENERIC = "generic",
  TWITTER = "twitter",
  ACADEMIC = "academic",
  PATENTS = "patents",
  LEXIS = "lexis",
}

export enum TypeEnum {
  USER = "user",
  BOT = "bot",
  RESOLVED = "resolved",
}

export enum ScopeTypeEnum {
  H = "H",
  R = "R",
}

export enum DefTypeEnum {
  EDISMAX = "edismax",
  LUCENE = "lucene",
  DISMAX = "dismax",
}

export enum OpEnum {
  OR = "OR",
  AND = "AND",
}

export enum ResolutionMethodEnum {
  MAJORITY = "majority",
  FIRST = "first",
}

export enum ResolutionStatusEnum {
  NEW = "NEW",
  CHANGED = "CHANGED",
  UNCHANGED = "UNCHANGED",
}

export enum TaskStatusEnum {
  PENDING = "PENDING",
  RUNNING = "RUNNING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
}

export enum ModeEnum {
  ALL = "ALL",
  ANY = "ANY",
}
