/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { CoreClient } from './CoreClient';


export type { AcademicAuthorModel } from './models/AcademicAuthorModel';
export type { AcademicItemModel } from './models/AcademicItemModel';
export type { AffiliationModel } from './models/AffiliationModel';
export type { AnnotatedItem } from './models/AnnotatedItem';
export type { AnnotationCollection } from './models/AnnotationCollection';
export type { AnnotationCollectionDBInput } from './models/AnnotationCollectionDBInput';
export type { AnnotationCollectionDBOutput } from './models/AnnotationCollectionDBOutput';
export type { AnnotationFiltersInput } from './models/AnnotationFiltersInput';
export type { AnnotationFiltersOutput } from './models/AnnotationFiltersOutput';
export type { AnnotationItem } from './models/AnnotationItem';
export type { AnnotationModelInput } from './models/AnnotationModelInput';
export type { AnnotationModelOutput } from './models/AnnotationModelOutput';
export type { AnnotationSchemeLabelChoiceFlat } from './models/AnnotationSchemeLabelChoiceFlat';
export type { AnnotationSchemeLabelChoiceInput } from './models/AnnotationSchemeLabelChoiceInput';
export type { AnnotationSchemeLabelChoiceOutput } from './models/AnnotationSchemeLabelChoiceOutput';
export { AnnotationSchemeLabelInput } from './models/AnnotationSchemeLabelInput';
export { AnnotationSchemeLabelOutput } from './models/AnnotationSchemeLabelOutput';
export type { AnnotationSchemeModelFlat } from './models/AnnotationSchemeModelFlat';
export type { AnnotationSchemeModelInput } from './models/AnnotationSchemeModelInput';
export type { AnnotationSchemeModelOutput } from './models/AnnotationSchemeModelOutput';
export type { AssignmentCounts } from './models/AssignmentCounts';
export type { AssignmentModelInput } from './models/AssignmentModelInput';
export type { AssignmentModelOutput } from './models/AssignmentModelOutput';
export type { AssignmentScopeModelInput } from './models/AssignmentScopeModelInput';
export type { AssignmentScopeModelOutput } from './models/AssignmentScopeModelOutput';
export { AssignmentScopeRandomConfigInput } from './models/AssignmentScopeRandomConfigInput';
export { AssignmentScopeRandomConfigOutput } from './models/AssignmentScopeRandomConfigOutput';
export { AssignmentScopeRandomWithExclusionConfigInput } from './models/AssignmentScopeRandomWithExclusionConfigInput';
export { AssignmentScopeRandomWithExclusionConfigOutput } from './models/AssignmentScopeRandomWithExclusionConfigOutput';
export { AssignmentStatus } from './models/AssignmentStatus';
export type { AuthTokenModel } from './models/AuthTokenModel';
export type { BasicProjectStats } from './models/BasicProjectStats';
export type { Body_login_for_access_token_api_login_token_post } from './models/Body_login_for_access_token_api_login_token_post';
export type { BotAnnotationMetaDataBaseModel } from './models/BotAnnotationMetaDataBaseModel';
export type { BotAnnotationModelInput } from './models/BotAnnotationModelInput';
export type { BotAnnotationModelOutput } from './models/BotAnnotationModelOutput';
export { BotKind } from './models/BotKind';
export { BotMetaResolve } from './models/BotMetaResolve';
export type { Cashtag } from './models/Cashtag';
export type { ContextAnnotation } from './models/ContextAnnotation';
export { Event } from './models/Event';
export type { ExampleEvent } from './models/ExampleEvent';
export type { ExampleSubEvent } from './models/ExampleSubEvent';
export { FlattenedAnnotationSchemeLabel } from './models/FlattenedAnnotationSchemeLabel';
export type { GenericItemModel } from './models/GenericItemModel';
export type { GroupedAnnotationsInput } from './models/GroupedAnnotationsInput';
export type { GroupedAnnotationsOutput } from './models/GroupedAnnotationsOutput';
export type { GroupedBotAnnotation } from './models/GroupedBotAnnotation';
export type { Hashtag } from './models/Hashtag';
export type { HighlighterModelInput } from './models/HighlighterModelInput';
export type { HighlighterModelOutput } from './models/HighlighterModelOutput';
export type { HistogramEntry } from './models/HistogramEntry';
export type { HTTPValidationError } from './models/HTTPValidationError';
export { ImportConfigJSONL } from './models/ImportConfigJSONL';
export type { ImportConfigScopus } from './models/ImportConfigScopus';
export { ImportConfigTwitterInput } from './models/ImportConfigTwitterInput';
export { ImportConfigTwitterOutput } from './models/ImportConfigTwitterOutput';
export type { ImportConfigWoS } from './models/ImportConfigWoS';
export type { ImportModelInput } from './models/ImportModelInput';
export type { ImportModelOutput } from './models/ImportModelOutput';
export { ImportType } from './models/ImportType';
export { ItemType } from './models/ItemType';
export type { ItemWithCount } from './models/ItemWithCount';
export type { Label } from './models/Label';
export type { LabelOptionsInput } from './models/LabelOptionsInput';
export type { LabelOptionsOutput } from './models/LabelOptionsOutput';
export type { MakeAssignmentsRequestModel } from './models/MakeAssignmentsRequestModel';
export type { Mention } from './models/Mention';
export type { ProgressIndicator } from './models/ProgressIndicator';
export type { ProgressIndicatorLabel } from './models/ProgressIndicatorLabel';
export type { ProjectBaseInfo } from './models/ProjectBaseInfo';
export type { ProjectBaseInfoEntry } from './models/ProjectBaseInfoEntry';
export type { ProjectBaseInfoScopeEntry } from './models/ProjectBaseInfoScopeEntry';
export type { ProjectInfo } from './models/ProjectInfo';
export type { ProjectModelInput } from './models/ProjectModelInput';
export type { ProjectModelOutput } from './models/ProjectModelOutput';
export type { ProjectPermissionsModelInput } from './models/ProjectPermissionsModelInput';
export type { ProjectPermissionsModelOutput } from './models/ProjectPermissionsModelOutput';
export type { QueryResult } from './models/QueryResult';
export type { RankEntry } from './models/RankEntry';
export { ReferencedTweet } from './models/ReferencedTweet';
export { ResolutionPayload } from './models/ResolutionPayload';
export type { ResolutionProposalResponse } from './models/ResolutionProposalResponse';
export type { SavedResolutionResponse } from './models/SavedResolutionResponse';
export type { SearchResult } from './models/SearchResult';
export type { TermStats } from './models/TermStats';
export type { TwitterItemModelInput } from './models/TwitterItemModelInput';
export type { TwitterItemModelOutput } from './models/TwitterItemModelOutput';
export type { TwitterUserModelInput } from './models/TwitterUserModelInput';
export type { TwitterUserModelOutput } from './models/TwitterUserModelOutput';
export type { URL } from './models/URL';
export type { UserBaseModel } from './models/UserBaseModel';
export type { UserInDBModel } from './models/UserInDBModel';
export type { UserModelInput } from './models/UserModelInput';
export type { UserModelOutput } from './models/UserModelOutput';
export type { UserPermission } from './models/UserPermission';
export type { UserProjectAssignmentScope } from './models/UserProjectAssignmentScope';
export type { ValidationError } from './models/ValidationError';

export { $AcademicAuthorModel } from './schemas/$AcademicAuthorModel';
export { $AcademicItemModel } from './schemas/$AcademicItemModel';
export { $AffiliationModel } from './schemas/$AffiliationModel';
export { $AnnotatedItem } from './schemas/$AnnotatedItem';
export { $AnnotationCollection } from './schemas/$AnnotationCollection';
export { $AnnotationCollectionDBInput } from './schemas/$AnnotationCollectionDBInput';
export { $AnnotationCollectionDBOutput } from './schemas/$AnnotationCollectionDBOutput';
export { $AnnotationFiltersInput } from './schemas/$AnnotationFiltersInput';
export { $AnnotationFiltersOutput } from './schemas/$AnnotationFiltersOutput';
export { $AnnotationItem } from './schemas/$AnnotationItem';
export { $AnnotationModelInput } from './schemas/$AnnotationModelInput';
export { $AnnotationModelOutput } from './schemas/$AnnotationModelOutput';
export { $AnnotationSchemeLabelChoiceFlat } from './schemas/$AnnotationSchemeLabelChoiceFlat';
export { $AnnotationSchemeLabelChoiceInput } from './schemas/$AnnotationSchemeLabelChoiceInput';
export { $AnnotationSchemeLabelChoiceOutput } from './schemas/$AnnotationSchemeLabelChoiceOutput';
export { $AnnotationSchemeLabelInput } from './schemas/$AnnotationSchemeLabelInput';
export { $AnnotationSchemeLabelOutput } from './schemas/$AnnotationSchemeLabelOutput';
export { $AnnotationSchemeModelFlat } from './schemas/$AnnotationSchemeModelFlat';
export { $AnnotationSchemeModelInput } from './schemas/$AnnotationSchemeModelInput';
export { $AnnotationSchemeModelOutput } from './schemas/$AnnotationSchemeModelOutput';
export { $AssignmentCounts } from './schemas/$AssignmentCounts';
export { $AssignmentModelInput } from './schemas/$AssignmentModelInput';
export { $AssignmentModelOutput } from './schemas/$AssignmentModelOutput';
export { $AssignmentScopeModelInput } from './schemas/$AssignmentScopeModelInput';
export { $AssignmentScopeModelOutput } from './schemas/$AssignmentScopeModelOutput';
export { $AssignmentScopeRandomConfigInput } from './schemas/$AssignmentScopeRandomConfigInput';
export { $AssignmentScopeRandomConfigOutput } from './schemas/$AssignmentScopeRandomConfigOutput';
export { $AssignmentScopeRandomWithExclusionConfigInput } from './schemas/$AssignmentScopeRandomWithExclusionConfigInput';
export { $AssignmentScopeRandomWithExclusionConfigOutput } from './schemas/$AssignmentScopeRandomWithExclusionConfigOutput';
export { $AssignmentStatus } from './schemas/$AssignmentStatus';
export { $AuthTokenModel } from './schemas/$AuthTokenModel';
export { $BasicProjectStats } from './schemas/$BasicProjectStats';
export { $Body_login_for_access_token_api_login_token_post } from './schemas/$Body_login_for_access_token_api_login_token_post';
export { $BotAnnotationMetaDataBaseModel } from './schemas/$BotAnnotationMetaDataBaseModel';
export { $BotAnnotationModelInput } from './schemas/$BotAnnotationModelInput';
export { $BotAnnotationModelOutput } from './schemas/$BotAnnotationModelOutput';
export { $BotKind } from './schemas/$BotKind';
export { $BotMetaResolve } from './schemas/$BotMetaResolve';
export { $Cashtag } from './schemas/$Cashtag';
export { $ContextAnnotation } from './schemas/$ContextAnnotation';
export { $Event } from './schemas/$Event';
export { $ExampleEvent } from './schemas/$ExampleEvent';
export { $ExampleSubEvent } from './schemas/$ExampleSubEvent';
export { $FlattenedAnnotationSchemeLabel } from './schemas/$FlattenedAnnotationSchemeLabel';
export { $GenericItemModel } from './schemas/$GenericItemModel';
export { $GroupedAnnotationsInput } from './schemas/$GroupedAnnotationsInput';
export { $GroupedAnnotationsOutput } from './schemas/$GroupedAnnotationsOutput';
export { $GroupedBotAnnotation } from './schemas/$GroupedBotAnnotation';
export { $Hashtag } from './schemas/$Hashtag';
export { $HighlighterModelInput } from './schemas/$HighlighterModelInput';
export { $HighlighterModelOutput } from './schemas/$HighlighterModelOutput';
export { $HistogramEntry } from './schemas/$HistogramEntry';
export { $HTTPValidationError } from './schemas/$HTTPValidationError';
export { $ImportConfigJSONL } from './schemas/$ImportConfigJSONL';
export { $ImportConfigScopus } from './schemas/$ImportConfigScopus';
export { $ImportConfigTwitterInput } from './schemas/$ImportConfigTwitterInput';
export { $ImportConfigTwitterOutput } from './schemas/$ImportConfigTwitterOutput';
export { $ImportConfigWoS } from './schemas/$ImportConfigWoS';
export { $ImportModelInput } from './schemas/$ImportModelInput';
export { $ImportModelOutput } from './schemas/$ImportModelOutput';
export { $ImportType } from './schemas/$ImportType';
export { $ItemType } from './schemas/$ItemType';
export { $ItemWithCount } from './schemas/$ItemWithCount';
export { $Label } from './schemas/$Label';
export { $LabelOptionsInput } from './schemas/$LabelOptionsInput';
export { $LabelOptionsOutput } from './schemas/$LabelOptionsOutput';
export { $MakeAssignmentsRequestModel } from './schemas/$MakeAssignmentsRequestModel';
export { $Mention } from './schemas/$Mention';
export { $ProgressIndicator } from './schemas/$ProgressIndicator';
export { $ProgressIndicatorLabel } from './schemas/$ProgressIndicatorLabel';
export { $ProjectBaseInfo } from './schemas/$ProjectBaseInfo';
export { $ProjectBaseInfoEntry } from './schemas/$ProjectBaseInfoEntry';
export { $ProjectBaseInfoScopeEntry } from './schemas/$ProjectBaseInfoScopeEntry';
export { $ProjectInfo } from './schemas/$ProjectInfo';
export { $ProjectModelInput } from './schemas/$ProjectModelInput';
export { $ProjectModelOutput } from './schemas/$ProjectModelOutput';
export { $ProjectPermissionsModelInput } from './schemas/$ProjectPermissionsModelInput';
export { $ProjectPermissionsModelOutput } from './schemas/$ProjectPermissionsModelOutput';
export { $QueryResult } from './schemas/$QueryResult';
export { $RankEntry } from './schemas/$RankEntry';
export { $ReferencedTweet } from './schemas/$ReferencedTweet';
export { $ResolutionPayload } from './schemas/$ResolutionPayload';
export { $ResolutionProposalResponse } from './schemas/$ResolutionProposalResponse';
export { $SavedResolutionResponse } from './schemas/$SavedResolutionResponse';
export { $SearchResult } from './schemas/$SearchResult';
export { $TermStats } from './schemas/$TermStats';
export { $TwitterItemModelInput } from './schemas/$TwitterItemModelInput';
export { $TwitterItemModelOutput } from './schemas/$TwitterItemModelOutput';
export { $TwitterUserModelInput } from './schemas/$TwitterUserModelInput';
export { $TwitterUserModelOutput } from './schemas/$TwitterUserModelOutput';
export { $URL } from './schemas/$URL';
export { $UserBaseModel } from './schemas/$UserBaseModel';
export { $UserInDBModel } from './schemas/$UserInDBModel';
export { $UserModelInput } from './schemas/$UserModelInput';
export { $UserModelOutput } from './schemas/$UserModelOutput';
export { $UserPermission } from './schemas/$UserPermission';
export { $UserProjectAssignmentScope } from './schemas/$UserProjectAssignmentScope';
export { $ValidationError } from './schemas/$ValidationError';

export { AnnotationsService } from './services/AnnotationsService';
export { DefaultService } from './services/DefaultService';
export { EventsService } from './services/EventsService';
export { ExportService } from './services/ExportService';
export { HighlightersService } from './services/HighlightersService';
export { ImportsService } from './services/ImportsService';
export { OauthService } from './services/OauthService';
export { ProjectService } from './services/ProjectService';
export { ProjectsService } from './services/ProjectsService';
export { SearchService } from './services/SearchService';
export { StatsService } from './services/StatsService';
export { UsersService } from './services/UsersService';
